GET http://localhost:8080/api/v1/outcomes HTTP/1.1
###

POST http://localhost:8080/api/v1/outcomes HTTP/1.1
Content-Type: application/json

{
  "description":"bills with bank",
  "amount": 101,
  "tax": 10,
  "is_payed": true,
  "company_name":"bank",
  "installment": 1,
  "total_installment":10,
  "paid_at": "2024-05-08T03:27:13Z",
  "category":"Food",
  "type": "Restaurant",
  "repeat": ""
}
###